apiVersion: v1
kind: Pod
metadata:
    labels:
        kaniko: true
spec:
    nodeSelector:
        role: worker
    imagePullSecrets:
      - name: cloud-vm114
    volumes:
      - name: helper-scripts
        emptyDir: {}
      - name: registry-credentials
        projected:
            sources:
            - secret:
                name: cloud-vm114-secret
                items: 
                - key: .dockerconfigjson
                  path: .docker/config.json
    initContainers:
      - name: fetch-helper-scripts
        image: alpine/git
        env:
            - name: "SCRIPTS_REPO"
              value: "https://baltig.infn.it/aceccant/helper-scripts.git"
        command: ['sh', '-c', 'git clone $SCRIPTS_REPO /helper-scripts']
        volumeMounts:
            - name: helper-scripts
              mountPath: /helper-scripts
    containers:
      - name: jnlp
        image: cloud-vm114.cloud.cnaf.infn.it/italiangrid/jnlp-slave-alpine:latest
        imagePullPolicy: Always
        resources:
            requests:
                memory: 500Mi
                cpu: 1
            limits:
                memory: 500Mi
                cpu: 1
      - name: runner
        image: gcr.io/kaniko-project/executor:debug
        imagePullPolicy: Always
        command:
          - /busybox/cat
        tty: true
        env:
            - name: "PATH" 
              value: "/helper-scripts/scripts:$PATH"
        volumeMounts:
          - name: registry-credentials
            mountPath: /root/
          - name: helper-scripts
            mountPath: /helper-scripts
        resources:
            requests:
                memory: 750Mi
                cpu: 1
            limits:
                memory: 2Gi
                cpu: 2
