apiVersion: v1
kind: Pod
metadata:
    labels:
        ci: true
spec:
    nodeSelector:
        zone: ci
    imagePullSecrets:
      - name: cloud-vm114
    volumes:
      - name: docker
        hostPath:
            path: /var/run/docker.sock
      - name: registry
        secret:
            secretName: registry-auth-basic
      - name: ssh
        secret:
            secretName: jenkins-ssh-keys
      - name: scratch
        persistentVolumeClaim:
            claimName: scratch-area-claim
      - name: m2-repository
        persistentVolumeClaim:
            claimName: m2-repository-claim
      - name: packages
        persistentVolumeClaim:
            claimName: packages-claim
    containers:
      - name: jnlp
        image: cloud-vm114.cloud.cnaf.infn.it/italiangrid/jnlp-slave-alpine:latest
        resources:
            requests:
                memory: 500Mi
                cpu: 1
            limits:
                memory: 500Mi
                cpu: 1
      - name: runner
        image: cloud-vm114.cloud.cnaf.infn.it/italiangrid/centos7-runner:latest
        command:
          - cat
        tty: true
        volumeMounts:
          - name: m2-repository
            mountPath: /home/jenkins/.m2
          - name: docker
            mountPath: /var/run/docker.sock
          - name: registry
            mountPath: /home/jenkins/.docker
          - name: ssh
            mountPath: /home/jenkins/.ssh
          - name: scratch
            mountPath: /srv/scratch
          - name: packages
            mountPath: /mnt/packages
        resources:
            requests:
                memory: 750Mi
                cpu: 1
            limits:
                memory: 2Gi
                cpu: 2
